source 'https://rubygems.org'

gem 'nokogiri'
gem 'mechanize'
gem 'sinatra'
gem 'awesome_print'
gem 'capistrano'
gem 'whenever', :require => false
gem 'data_mapper'
gem 'dm-mysql-adapter'
gem 'mysql'
gem 'haml'
gem 'shotgun'
gem 'activesupport'
gem 'rake'
